
name: ligo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26
  - scipy=1.11
  - matplotlib=3.8
  - h5py=3.10
  - ipykernel=6.29
  - jupyterlab=4.1
  - notebook=7.1
  - decorator=4.4
  - pip
  - pip:
      - ipympl==0.9.*
